global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'recommendation_service'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'online_metrics_collector'
    static_configs:
      - targets: ['localhost:9000']
